// components/storyblok/fields/Blocks.vue
<template>
  <div>
    <component
      :is="blok.component | dashify"
      v-for="blok in blocks"
      :key="blok._uid"
      :blok="blok"
    />
  </div>
</template>

<script>
export default {
  props: {
    blocks: {
      type: Array,
      required: true
    }
  }
}
</script>

// src/features/common/Blocks/index.tsx
import type { BlockComponent } from './Block'
import Block from './Block'

export interface Props {
  bloks?: BlockComponent[]
}

export default function Blocks({ bloks }: Props) {
  if (!bloks) {
    return null
  }

  return (
    <>
      {bloks.map((blok) => {
        return <Block blok={blok} key={blok._uid} />
      })}
    </>
  )
}
